In [1]:
#import libraries
import psycopg2
import pandas as pd
import numpy as np

In [2]:
#write code for loading csv to pandas

   index User ID Vehicle Model  Battery Capacity (kWh) Charging Station ID  \
0      0  User_1        BMW i3              108.463007         Station_391
1      1  User_2  Hyundai Kona              100.000000         Station_428
2      2  User_3    Chevy Bolt               75.000000         Station_181
3      3  User_4  Hyundai Kona               50.000000         Station_327
4      4  User_5  Hyundai Kona               50.000000         Station_108

  Charging Station Location  Charging Start Time    Charging End Time  \
0                   Houston  2024-01-01 00:00:00  2024-01-01 00:39:00
1             San Francisco  2024-01-01 01:00:00  2024-01-01 03:01:00
2             San Francisco  2024-01-01 02:00:00  2024-01-01 04:48:00
3                   Houston  2024-01-01 03:00:00  2024-01-01 06:42:00
4               Los Angeles  2024-01-01 04:00:00  2024-01-01 05:46:00

   Energy Consumed (kWh)  Charging Duration (hours)  ...  Charging Cost (USD)  \
0              60.712346                   0.591363  ...            13.087717
1              12.339275                   3.133652  ...            21.128448
2              19.128876                   2.452653  ...            35.667270
3              79.457824                   1.266431  ...            13.036239
4              19.629104                   2.019765  ...            10.161471

   Time of Day Day of Week State of Charge (Start %)  State of Charge (End %)  \
0      Evening     Tuesday                 29.371576                86.119962
1      Morning      Monday                 10.115778                84.664344
2      Morning    Thursday                  6.854604                69.917615
3      Evening    Saturday                 83.120003                99.624328
4      Morning    Saturday                 54.258950                63.743786

   Distance Driven (since last charge) (km)  Temperature (°C)  \
0                                293.602111         27.947953
1                                112.112804         14.311026
2                                 71.799253         21.002002
3                                199.577785         38.316313
4                                203.661847         -7.834199

   Vehicle Age (years)     Charger Type               User Type
0                  2.0  DC Fast Charger                Commuter
1                  3.0          Level 1           Casual Driver
2                  2.0          Level 2                Commuter
3                  1.0          Level 1  Long-Distance Traveler
4                  1.0          Level 1  Long-Distance Traveler

[5 rows x 21 columns]

C:\Users\jismo\AppData\Local\Temp\ipykernel_228512\2804113529.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql_query, conn, params=params)

In [3]:
#shape
chargingstationdata.shape

(1320, 21)

In [4]:
#information
chargingstationdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1320 entries, 0 to 1319
Data columns (total 21 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   index                                     1320 non-null   int64
 1   User ID                                   1320 non-null   object
 2   Vehicle Model                             1320 non-null   object
 3   Battery Capacity (kWh)                    1320 non-null   float64
 4   Charging Station ID                       1320 non-null   object
 5   Charging Station Location                 1320 non-null   object
 6   Charging Start Time                       1320 non-null   object
 7   Charging End Time                         1320 non-null   object
 8   Energy Consumed (kWh)                     1254 non-null   float64
 9   Charging Duration (hours)                 1320 non-null   float64
 10  Charging Rate (kW)                        1254 non-null   float64
 11  Charging Cost (USD)                       1320 non-null   float64
 12  Time of Day                               1320 non-null   object
 13  Day of Week                               1320 non-null   object
 14  State of Charge (Start %)                 1320 non-null   float64
 15  State of Charge (End %)                   1320 non-null   float64
 16  Distance Driven (since last charge) (km)  1254 non-null   float64
 17  Temperature (°C)                          1320 non-null   float64
 18  Vehicle Age (years)                       1320 non-null   float64
 19  Charger Type                              1320 non-null   object
 20  User Type                                 1320 non-null   object
dtypes: float64(10), int64(1), object(10)
memory usage: 216.7+ KB

In [5]:
#descriptive statistics
chargingstationdata.describe()

,index,Battery Capacity (kWh),Energy Consumed (kWh),Charging Duration (hours),Charging Rate (kW),Charging Cost (USD),State of Charge (Start %),State of Charge (End %),Distance Driven (since last charge) (km),Temperature (°C),Vehicle Age (years)
count,1320.000000,1320.000000,1254.000000,1320.000000,1254.000000,1320.000000,1320.000000,1320.000000,1254.000000,1320.000000,1320.000000
mean,659.500000,74.534692,42.642894,2.269377,25.963003,22.551352,49.130012,75.141590,153.596788,15.263591,3.612843
std,381.195488,20.626914,22.411705,1.061037,14.011326,10.751494,24.074134,17.080580,86.004987,14.831216,2.309824
min,0.000000,1.532807,0.045772,0.095314,1.472549,0.234317,2.325959,7.604224,0.862361,-10.724770,0.000000
25%,329.750000,62.000000,23.881193,1.397623,13.856583,13.368141,27.786903,62.053266,79.445335,2.800664,2.000000
50%,659.500000,75.000000,42.691405,2.258136,25.603799,22.076360,48.241771,75.682496,152.259867,14.630846,4.000000
75%,989.250000,85.000000,61.206218,3.112806,37.502998,31.646044,69.277921,88.201370,226.073284,27.981810,6.000000
max,1319.000000,193.003074,152.238758,7.635145,97.342255,69.407743,152.489761,177.708666,398.364775,73.169588,11.688592

In [6]:
#finding missing value
chargingstationdata.isnull().sum()

index                                        0
User ID                                      0
Vehicle Model                                0
Battery Capacity (kWh)                       0
Charging Station ID                          0
Charging Station Location                    0
Charging Start Time                          0
Charging End Time                            0
Energy Consumed (kWh)                       66
Charging Duration (hours)                    0
Charging Rate (kW)                          66
Charging Cost (USD)                          0
Time of Day                                  0
Day of Week                                  0
State of Charge (Start %)                    0
State of Charge (End %)                      0
Distance Driven (since last charge) (km)    66
Temperature (°C)                             0
Vehicle Age (years)                          0
Charger Type                                 0
User Type                                    0
dtype: int64

In [7]:
#percentage of missing value
chargingstationdata.isnull().sum()/chargingstationdata.shape[0]*100

index                                       0.0
User ID                                     0.0
Vehicle Model                               0.0
Battery Capacity (kWh)                      0.0
Charging Station ID                         0.0
Charging Station Location                   0.0
Charging Start Time                         0.0
Charging End Time                           0.0
Energy Consumed (kWh)                       5.0
Charging Duration (hours)                   0.0
Charging Rate (kW)                          5.0
Charging Cost (USD)                         0.0
Time of Day                                 0.0
Day of Week                                 0.0
State of Charge (Start %)                   0.0
State of Charge (End %)                     0.0
Distance Driven (since last charge) (km)    5.0
Temperature (°C)                            0.0
Vehicle Age (years)                         0.0
Charger Type                                0.0
User Type                                   0.0
dtype: float64

In [14]:
chargingstationdata.dropna(subset=['Energy Consumed (kWh)','Charging Rate (kW) ', 'Distance Driven (since last charge) (km)'], inplace=True)

KeyError: ['Charging Rate (kW) ']

In [8]:
#All columns in the dataframe
chargingstationdata.columns

Index(['index', 'User ID', 'Vehicle Model', 'Battery Capacity (kWh)',
       'Charging Station ID', 'Charging Station Location',
       'Charging Start Time', 'Charging End Time', 'Energy Consumed (kWh)',
       'Charging Duration (hours)', 'Charging Rate (kW)',
       'Charging Cost (USD)', 'Time of Day', 'Day of Week',
       'State of Charge (Start %)', 'State of Charge (End %)',
       'Distance Driven (since last charge) (km)', 'Temperature (°C)',
       'Vehicle Age (years)', 'Charger Type', 'User Type'],
      dtype='object')

In [9]:
# Convert time columns to datetime
chargingstationdata['Charging Start Time'] = pd.to_datetime(df['Charging Start Time'])
chargingstationdata['Charging End Time'] = pd.to_datetime(df['Charging End Time'])

# Extract more time features
chargingstationdata['Charging Hour'] = chargingstationdata['Charging Start Time'].dt.hour['Charging Hour'] = chargingstationdata['Charging Start Time'].dt.hour['Charging Hour'] = chargingstationdata['Charging Start Time'].dt.hour['Charging Month'] = chargingstationdata['Charging Start Time'].dt.month
chargingstationdata['Charging Day'] = chargingstationdata['Charging Start Time'].dt.day
chargingstationdata['Is Weekend'] = chargingstationdata['Charging Start Time'].dt.dayofweek >= 5

In [10]:
chargingstationdata.head()

,index,User ID,Vehicle Model,Battery Capacity (kWh),Charging Station ID,Charging Station Location,Charging Start Time,Charging End Time,Energy Consumed (kWh),Charging Duration (hours),...,State of Charge (End %),Distance Driven (since last charge) (km),Temperature (°C),Vehicle Age (years),Charger Type,User Type,Charging Hour,Charging Month,Charging Day,Is Weekend
0,0,User_1,BMW i3,108.463007,Station_391,Houston,2024-01-01 00:00:00,2024-01-01 00:39:00,60.712346,0.591363,...,86.119962,293.602111,27.947953,2.0,DC Fast Charger,Commuter,0,1,1,False
1,1,User_2,Hyundai Kona,100.000000,Station_428,San Francisco,2024-01-01 01:00:00,2024-01-01 03:01:00,12.339275,3.133652,...,84.664344,112.112804,14.311026,3.0,Level 1,Casual Driver,1,1,1,False
2,2,User_3,Chevy Bolt,75.000000,Station_181,San Francisco,2024-01-01 02:00:00,2024-01-01 04:48:00,19.128876,2.452653,...,69.917615,71.799253,21.002002,2.0,Level 2,Commuter,2,1,1,False
3,3,User_4,Hyundai Kona,50.000000,Station_327,Houston,2024-01-01 03:00:00,2024-01-01 06:42:00,79.457824,1.266431,...,99.624328,199.577785,38.316313,1.0,Level 1,Long-Distance Traveler,3,1,1,False
4,4,User_5,Hyundai Kona,50.000000,Station_108,Los Angeles,2024-01-01 04:00:00,2024-01-01 05:46:00,19.629104,2.019765,...,63.743786,203.661847,-7.834199,1.0,Level 1,Long-Distance Traveler,4,1,1,False

In [11]:
# Charging rate (kW)
chargingstationdata['Charging Rate'] = chargingstationdata['Energy Consumed (kWh)'] / chargingstationdata['Charging Duration (hours)']

# Battery percentage charged
chargingstationdata['SOC Difference'] = chargingstationdata['State of Charge (End %)'] - chargingstationdata['State of Charge (Start %)']

# Efficiency ratio
chargingstationdata['Efficiency Ratio'] = chargingstationdata['SOC Difference'] / chargingstationdata['Energy Consumed (kWh)']

In [ ]:
# One-hot encode categorical variables
dchargingstationdataf = pd.get_dummies(chargingstationdata, columns=['Vehicle Model', 'Charging Station Location', 
                                'Time of Day', 'Day of Week', 'Charger Type', 
                                'User Type'])