In [1]:
#import libraries
import psycopg2
import pandas as pd
import numpy as np
import re

In [2]:
#Reading data from postgresql

# Establish connection
conn = psycopg2.connect(
    host="localhost",
    database="APDV",
    user="postgres",
    password="Nevin"
)

# Define query
sql_query = "SELECT * FROM airquality"

# Execute with parameters
params = ('value',)
airqualitydata = pd.read_sql(sql_query, conn, params=params)

# Display results
print(airqualitydata.head())

# Close connection
conn.close()

   index  state_code  county_code  site_number  parameter_code  poc parameter  \
0      0           1            3           10           44201    1     Ozone
1      1           1            3           10           44201    1     Ozone
2      2           1           49         9991           44201    1     Ozone
3      3           1           51            4           44201    1     Ozone
4      4           1           51            4           44201    1     Ozone

    si_id  method_code                                method  ... state_name  \
0       7           87  INSTRUMENTAL-ULTRA VIOLET ABSORPTION  ...    Alabama
1       7           87  INSTRUMENTAL-ULTRA VIOLET ABSORPTION  ...    Alabama
2   96297           47             INSTRUMENTAL-ULTRA VIOLET  ...    Alabama
3  104232           87  INSTRUMENTAL-ULTRA VIOLET ABSORPTION  ...    Alabama
4  104232           87  INSTRUMENTAL-ULTRA VIOLET ABSORPTION  ...    Alabama

   county_name   city_name cbsa_code                  cbsa_name  csa_code  \
0      Baldwin    Fairhope   19300.0  Daphne-Fairhope-Foley, AL     380.0
1      Baldwin    Fairhope   19300.0  Daphne-Fairhope-Foley, AL     380.0
2       DeKalb  Crossville   22840.0             Fort Payne, AL       NaN
3       Elmore    Wetumpka   33860.0             Montgomery, AL       NaN
4       Elmore    Wetumpka   33860.0             Montgomery, AL       NaN

                     csa_name  tribal_code  tribe_name  date_of_last_change
0  Mobile-Daphne-Fairhope, AL          NaN        None           2024-07-18
1  Mobile-Daphne-Fairhope, AL          NaN        None           2025-04-10
2                        None          NaN        None           2024-11-04
3                        None          NaN        None           2024-07-18
4                        None          NaN        None           2025-04-15

[5 rows x 59 columns]

C:\Users\jismo\AppData\Local\Temp\ipykernel_6640\1500258671.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  airqualitydata = pd.read_sql(sql_query, conn, params=params)

In [3]:
airqualitydata.shape

(3738, 59)

In [4]:
#information
airqualitydata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3738 entries, 0 to 3737
Data columns (total 59 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   index                           3738 non-null   int64
 1   state_code                      3738 non-null   int64
 2   county_code                     3738 non-null   int64
 3   site_number                     3738 non-null   int64
 4   parameter_code                  3738 non-null   int64
 5   poc                             3738 non-null   int64
 6   parameter                       3738 non-null   object
 7   si_id                           3738 non-null   int64
 8   method_code                     3738 non-null   int64
 9   method                          3738 non-null   object
 10  assessment_date                 3738 non-null   object
 11  assessment_number               3738 non-null   float64
 12  unit_code                       3738 non-null   int64
 13  unit                            3738 non-null   object
 14  lvl1_monitor_concentration      1011 non-null   float64
 15  lvl1_assessment_concentration   1013 non-null   float64
 16  lvl2_monitor_concentration      2601 non-null   float64
 17  lvl2_assessment_concentration   2601 non-null   float64
 18  lvl3_monitor_concentration      1910 non-null   float64
 19  lvl3_assessment_concentration   1910 non-null   float64
 20  lvl4_monitor_concentration      2440 non-null   float64
 21  lvl4_assessment_concentration   2439 non-null   float64
 22  lvl5_monitor_concentration      2422 non-null   float64
 23  lvl5_assessment_concentration   2421 non-null   float64
 24  lvl6_monitor_concentration      1606 non-null   float64
 25  lvl6_assessment_concentration   1604 non-null   float64
 26  lvl7_monitor_concentration      1085 non-null   float64
 27  lvl7_assessment_concentration   1083 non-null   float64
 28  lvl8_monitor_concentration      528 non-null    float64
 29  lvl8_assessment_concentration   528 non-null    float64
 30  lvl9_monitor_concentration      177 non-null    float64
 31  lvl9_assessment_concentration   177 non-null    float64
 32  lvl10_monitor_concentration     107 non-null    float64
 33  lvl10_assessment_concentration  107 non-null    float64
 34  pqao_code                       3738 non-null   int64
 35  pqao                            3738 non-null   object
 36  monitoring_agency_code          3738 non-null   int64
 37  monitoring_agency               3738 non-null   object
 38  performing_agency_code          3738 non-null   int64
 39  performing_agency               3738 non-null   object
 40  analyzing_agency_code           3201 non-null   object
 41  analyzing_agency                3201 non-null   object
 42  auditing_agency_code            0 non-null      object
 43  auditing_agency                 0 non-null      object
 44  latitude                        3738 non-null   float64
 45  longitude                       3738 non-null   float64
 46  datum                           3738 non-null   object
 47  local_site_name                 3632 non-null   object
 48  address                         3738 non-null   object
 49  state_name                      3738 non-null   object
 50  county_name                     3738 non-null   object
 51  city_name                       3738 non-null   object
 52  cbsa_code                       3424 non-null   float64
 53  cbsa_name                       3424 non-null   object
 54  csa_code                        2627 non-null   float64
 55  csa_name                        2627 non-null   object
 56  tribal_code                     62 non-null     float64
 57  tribe_name                      62 non-null     object
 58  date_of_last_change             3738 non-null   object
dtypes: float64(26), int64(12), object(21)
memory usage: 1.7+ MB

In [5]:
#descriptive statistics
airqualitydata.describe()

,index,state_code,county_code,site_number,parameter_code,poc,si_id,method_code,assessment_number,unit_code,...,lvl10_monitor_concentration,lvl10_assessment_concentration,pqao_code,monitoring_agency_code,performing_agency_code,latitude,longitude,cbsa_code,csa_code,tribal_code
count,3738.000000,3738.000000,3738.000000,3738.000000,3738.000000,3738.000000,3738.000000,3738.000000,3738.000000,3738.000000,...,107.000000,107.000000,3738.000000,3738.000000,3738.000000,3738.000000,3738.000000,3424.000000,2627.000000,62.000000
mean,1868.500000,28.809791,75.918406,1014.312199,43371.620385,1.183521,48208.440075,164.764580,1.026217,7.553772,...,193.063675,193.035850,779.007758,756.154093,775.318887,38.524583,-91.406361,30903.457944,343.518462,563.983871
std,1079.211981,15.275349,83.187860,2209.350815,891.179367,0.616017,44839.736261,180.245929,0.226331,0.497167,...,118.816449,120.313015,370.665293,339.934630,363.887953,4.667703,15.870097,10982.756190,126.476128,331.277631
min,0.000000,1.000000,1.000000,1.000000,42101.000000,1.000000,7.000000,9.000000,1.000000,7.000000,...,0.210000,0.212000,13.000000,12.000000,9.000000,19.060655,-159.366240,10220.000000,104.000000,17.000000
25%,934.250000,17.000000,21.000000,8.000000,42401.000000,1.000000,7124.750000,74.000000,1.000000,7.000000,...,161.900000,165.100000,584.000000,584.000000,584.000000,35.503199,-103.273777,19780.000000,216.000000,413.500000
50%,1868.500000,30.000000,59.000000,40.000000,44201.000000,1.000000,15415.000000,87.000000,1.000000,8.000000,...,249.000000,249.000000,768.000000,768.000000,768.000000,39.469219,-87.524047,33500.000000,370.000000,750.000000
75%,2802.750000,40.000000,103.000000,1005.750000,44201.000000,1.000000,96337.500000,100.000000,1.000000,8.000000,...,253.000000,250.000000,1035.000000,1001.000000,1035.000000,41.601899,-78.768924,39900.000000,430.000000,750.000000
max,3737.000000,56.000000,800.000000,9997.000000,44201.000000,9.000000,105404.000000,600.000000,4.000000,8.000000,...,415.000000,416.000000,6532.000000,6532.000000,2368.000000,64.845690,-67.061325,49740.000000,566.000000,905.000000

# Missing Data Handling

In [7]:
#percentage of missing value
airqualitydata.isnull().sum()/airqualitydata.shape[0]*100

index                               0.000000
state_code                          0.000000
county_code                         0.000000
site_number                         0.000000
parameter_code                      0.000000
poc                                 0.000000
parameter                           0.000000
si_id                               0.000000
method_code                         0.000000
method                              0.000000
assessment_date                     0.000000
assessment_number                   0.000000
unit_code                           0.000000
unit                                0.000000
lvl1_monitor_concentration         72.953451
lvl1_assessment_concentration      72.899946
lvl2_monitor_concentration         30.417335
lvl2_assessment_concentration      30.417335
lvl3_monitor_concentration         48.903157
lvl3_assessment_concentration      48.903157
lvl4_monitor_concentration         34.724452
lvl4_assessment_concentration      34.751204
lvl5_monitor_concentration         35.205993
lvl5_assessment_concentration      35.232745
lvl6_monitor_concentration         57.035848
lvl6_assessment_concentration      57.089353
lvl7_monitor_concentration         70.973783
lvl7_assessment_concentration      71.027287
lvl8_monitor_concentration         85.874799
lvl8_assessment_concentration      85.874799
lvl9_monitor_concentration         95.264848
lvl9_assessment_concentration      95.264848
lvl10_monitor_concentration        97.137507
lvl10_assessment_concentration     97.137507
pqao_code                           0.000000
pqao                                0.000000
monitoring_agency_code              0.000000
monitoring_agency                   0.000000
performing_agency_code              0.000000
performing_agency                   0.000000
analyzing_agency_code              14.365971
analyzing_agency                   14.365971
auditing_agency_code              100.000000
auditing_agency                   100.000000
latitude                            0.000000
longitude                           0.000000
datum                               0.000000
local_site_name                     2.835741
address                             0.000000
state_name                          0.000000
county_name                         0.000000
city_name                           0.000000
cbsa_code                           8.400214
cbsa_name                           8.400214
csa_code                           29.721776
csa_name                           29.721776
tribal_code                        98.341359
tribe_name                         98.341359
date_of_last_change                 0.000000
dtype: float64

In [8]:
def handle_missing_values(airqualitydata):
    """
    Handle missing values in a DataFrame with proper type checking
    """
    airqualitydata_clean = airqualitydata.copy()
    
    # 1. Drop high-missing columns
    cols_to_drop = [
        'auditing_agency_code', 'auditing_agency',
        'tribal_code', 'tribe_name',
        'lvl10_monitor_concentration', 'lvl10_assessment_concentration',
        'lvl9_monitor_concentration', 'lvl9_assessment_concentration'
    ]
    cols_to_drop = [col for col in cols_to_drop if col in airqualitydata_clean.columns]
    airqualitydata_clean = airqualitydata_clean.drop(columns=cols_to_drop)
    
    # 2. Process each column with type-specific handling
    for col in airqualitydata_clean.columns:
        if airqualitydata_clean[col].isna().sum() > 0:  # Only process columns with missing values
            try:
                # For numeric columns
                if pd.api.types.is_numeric_dtype(airqualitydata_clean[col]):
                    # Create missing indicator for concentration columns
                    if 'concentration' in col:
                        airqualitydata_clean[f'{col}_missing'] = airqualitydata_clean[col].isna().astype(int)
                    # Fill with median for numeric
                    median_val = airqualitydata_clean[col].median()
                    airqualitydata_clean[col] = airqualitydata_clean[col].fillna(median_val)
                
                # For string/object columns
                elif pd.api.types.is_string_dtype(airqualitydata_clean[col]):
                    mode_val = airqualitydata_clean[col].mode()[0] if not airqualitydata_clean[col].mode().empty else 'Unknown'
                    airqualitydata_clean[col] = airqualitydata_clean[col].fillna(mode_val)
                
                # For datetime columns
                elif pd.api.types.is_datetime64_any_dtype(airqualitydata_clean[col]):
                    airqualitydata_clean[col] = airqualitydata_clean[col].fillna(method='ffill')
                
            except Exception as e:
                print(f"Could not process column {col}: {str(e)}")
                # Fallback to simple fill for problematic columns
                airqualitydata_clean[col] = airqualitydata_clean[col].fillna('Unknown') if pd.api.types.is_string_dtype(airqualitydata_clean[col]) else airqualitydata_clean[col].fillna(0)
    
    return airqualitydata_clean

In [9]:
# Process missing values
airqualitydata_clean = handle_missing_values(airqualitydata)

In [10]:
#percentage of missing value
airqualitydata_clean.isnull().sum()/airqualitydata_clean.shape[0]*100

index                                    0.0
state_code                               0.0
county_code                              0.0
site_number                              0.0
parameter_code                           0.0
                                        ...
lvl6_assessment_concentration_missing    0.0
lvl7_monitor_concentration_missing       0.0
lvl7_assessment_concentration_missing    0.0
lvl8_monitor_concentration_missing       0.0
lvl8_assessment_concentration_missing    0.0
Length: 67, dtype: float64

# Transformantion

In [12]:
airqualitydata_clean.head()

,index,state_code,county_code,site_number,parameter_code,poc,parameter,si_id,method_code,method,...,lvl4_monitor_concentration_missing,lvl4_assessment_concentration_missing,lvl5_monitor_concentration_missing,lvl5_assessment_concentration_missing,lvl6_monitor_concentration_missing,lvl6_assessment_concentration_missing,lvl7_monitor_concentration_missing,lvl7_assessment_concentration_missing,lvl8_monitor_concentration_missing,lvl8_assessment_concentration_missing
0,0,1,3,10,44201,1,Ozone,7,87,INSTRUMENTAL-ULTRA VIOLET ABSORPTION,...,0,0,0,0,1,1,1,1,0,0
1,1,1,3,10,44201,1,Ozone,7,87,INSTRUMENTAL-ULTRA VIOLET ABSORPTION,...,0,0,0,0,1,1,1,1,0,0
2,2,1,49,9991,44201,1,Ozone,96297,47,INSTRUMENTAL-ULTRA VIOLET,...,0,0,1,1,0,0,1,1,1,1
3,3,1,51,4,44201,1,Ozone,104232,87,INSTRUMENTAL-ULTRA VIOLET ABSORPTION,...,0,0,0,0,1,1,1,1,0,0
4,4,1,51,4,44201,1,Ozone,104232,87,INSTRUMENTAL-ULTRA VIOLET ABSORPTION,...,0,0,0,0,1,1,1,1,0,0

In [13]:
#Finding unique values in method column
airqualitydata_clean.method.value_counts()

method
INSTRUMENTAL-ULTRA VIOLET ABSORPTION                                                                                   1236
INSTRUMENTAL-ULTRA VIOLET                                                                                               713
INSTRUMENTAL-GAS PHASE CHEMILUMINESCENCE                                                                                265
INSTRUMENTAL-ULTRAVIOLET FLUORESCENCE                                                                                   226
INSTRUMENTAL-PULSED FLUORESCENT                                                                                         166
INSTRUMENTAL-Pulsed Fluorescent 43C-TLE/43i-TLE                                                                         153
Teledyne Model T500U-Cavity Attenuated Phase Shift Spectroscopy                                                         133
INSTRUMENTAL-CHEMILUMINESCENCE                                                                                          125
Instrumental - Teledyne API - Model N500-Cavity-Attenuated Phase-Shift (CAPS) spectroscopy Nitrogen Oxides Analyzer     115
INSTRUMENTAL-Gas Filter Correlation Teledyne API 300 EU / T300U                                                         105
Instrumental-Ultraviolet Fluorescence API 100 EU                                                                         92
INSTRUMENTAL-Gas Filter Correlation Thermo Electron 48i-TLE                                                              91
Instrumental-Chemiluminescence Thermo Electron 42C-TL, 42i-TL                                                            86
INSTRUMENTAL-GAS FILTER CORRELATION CO ANALYZER                                                                          79
INSTRUMENTAL-NONDISPERSIVE INFRARED                                                                                      39
Instrumental-Chemiluminescence Teledyne API 200 EU/501                                                                   36
Instrumental-Chemiluminescence API Model 265E and T265                                                                   19
INSTRUMENTAL-NONDISPERSIVE INFRARED PHOTOMETRY                                                                           15
Teledyne-API Model 200EUP or T200UP-Photolytic-Chemiluminescence                                                         13
INSTRUMENTAL-ULTRAVIOLET ABSORPTION                                                                                       7
Instrumental-Chemiluminescence                                                                                            6
INSTRUMENTAL-Gas Filter Correlation Ecotech EC9830T                                                                       3
INSTRUMENTAL-UV absorption photometry                                                                                     3
Instrumental-Ultraviolet Fluorescence EC9850T                                                                             3
INSTRUMENTAL-FLUORESCENCE DETECTION                                                                                       3
INSTRUMENTAL-ULTRAVIOLET RADIATION ABSORBTN                                                                               2
Instrumental-Ecotech Serinus 10                                                                                           2
Instrumental-UV absorption photometry/UV 2B model 202 and 205                                                             2
Name: count, dtype: int64

In [14]:
#Clean Method Names
airqualitydata_clean['method_clean'] = (
    airqualitydata_clean['method']
    .str.replace(
        r'(?i)(instrumental|analyzer)[\s\-]*(ultra[\s\-]*violet|uv)', 
        'UV', 
        regex=True
    )
    .str.replace(r'(?i)\b(absorption|spectrometry|analysis)\b', '', regex=True)
    .str.strip()
    .replace('', 'UV Method')
)

In [15]:
airqualitydata_clean.head()

,index,state_code,county_code,site_number,parameter_code,poc,parameter,si_id,method_code,method,...,lvl4_assessment_concentration_missing,lvl5_monitor_concentration_missing,lvl5_assessment_concentration_missing,lvl6_monitor_concentration_missing,lvl6_assessment_concentration_missing,lvl7_monitor_concentration_missing,lvl7_assessment_concentration_missing,lvl8_monitor_concentration_missing,lvl8_assessment_concentration_missing,method_clean
0,0,1,3,10,44201,1,Ozone,7,87,INSTRUMENTAL-ULTRA VIOLET ABSORPTION,...,0,0,0,1,1,1,1,0,0,UV
1,1,1,3,10,44201,1,Ozone,7,87,INSTRUMENTAL-ULTRA VIOLET ABSORPTION,...,0,0,0,1,1,1,1,0,0,UV
2,2,1,49,9991,44201,1,Ozone,96297,47,INSTRUMENTAL-ULTRA VIOLET,...,0,1,1,0,0,1,1,1,1,UV
3,3,1,51,4,44201,1,Ozone,104232,87,INSTRUMENTAL-ULTRA VIOLET ABSORPTION,...,0,0,0,1,1,1,1,0,0,UV
4,4,1,51,4,44201,1,Ozone,104232,87,INSTRUMENTAL-ULTRA VIOLET ABSORPTION,...,0,0,0,1,1,1,1,0,0,UV

In [16]:
#Create Composite Site ID
airqualitydata_clean['site_id'] = (
    airqualitydata_clean['state_code'].astype(str).str.zfill(2) + '-' +
    airqualitydata_clean['county_code'].astype(str).str.zfill(3) + '-' +
    airqualitydata_clean['site_number'].astype(str).str.zfill(4)
)

In [17]:
# Extract Measurement Precision from Method
airqualitydata_clean['precision_code'] = (
    airqualitydata_clean['method']
    .str.extract(r'(\bCLASS\s*[IVX]+|\bPRECISION\s*\d+)', flags=re.IGNORECASE)
    .squeeze()
)

In [18]:
#Flag Incomplete Monitoring Data
missing_cols = [col for col in airqualitydata_clean.columns if 'missing' in col]
airqualitydata_clean['data_completeness'] = 1 - (airqualitydata_clean[missing_cols].sum(axis=1) / len(missing_cols))

In [19]:
#Categorize by Data Quality
conditions = [
    airqualitydata_clean['data_completeness'] >= 0.9,
    airqualitydata_clean['data_completeness'] >= 0.5,
]
choices = ['High', 'Medium']
airqualitydata_clean['quality_category'] = np.select(conditions, choices, default='Low')

In [20]:
#Parse Concentration Ranges
airqualitydata_clean['lvl1_monitor_concentration_clean'] = (
    airqualitydata_clean['lvl1_monitor_concentration']
    .astype(str)
    .str.extract(r'([<>]?)(\d+\.?\d*)')
    .apply(lambda x: 
        float(x[1]) * (-1 if x[0] == '<' else 1 if x[0] == '>' else 1), 
        axis=1
    )
)

In [21]:
airqualitydata_clean['has_lvl8_data'] = airqualitydata_clean['lvl8_monitor_concentration_missing'].eq(0).astype(int)

In [22]:
airqualitydata_clean['concentration_trend'] = (
    airqualitydata_clean.groupby('site_id')['lvl1_monitor_concentration']
    .transform(lambda x: x.diff().rolling(3, min_periods=1).mean())
)

In [23]:
airqualitydata_clean['agency_type'] = (
    airqualitydata_clean['monitoring_agency_code']
    .astype(str)
    .str.extract(r'^([A-Z]+)')[0]
    .replace({'EPA': 'Federal', 'STATE': 'State', None: 'Local'})
)

In [24]:
airqualitydata_clean['display_text'] = (
    "Site " + airqualitydata_clean['site_number'].astype(str) + 
    " (" + airqualitydata_clean['parameter'] + "): " + 
    airqualitydata_clean['lvl1_monitor_concentration'].round(2).astype(str) + " " + 
    airqualitydata_clean['unit'].fillna('ppm')
)

In [25]:
# Target encoding for counties
county_means = airqualitydata_clean.groupby('county_code')['lvl1_monitor_concentration'].mean().to_dict()
airqualitydata_clean['county_encoded'] = airqualitydata_clean['county_code'].map(county_means)

# Frequency encoding for parameters
param_freq = airqualitydata_clean['parameter'].value_counts(normalize=True).to_dict()
airqualitydata_clean['param_freq_encoded'] = airqualitydata_clean['parameter'].map(param_freq)

In [26]:
# Convert to datetime if not already
airqualitydata_clean['date_of_last_change'] = pd.to_datetime(airqualitydata_clean['date_of_last_change'])

# Extract temporal components
airqualitydata_clean['change_year'] = airqualitydata_clean['date_of_last_change'].dt.year
airqualitydata_clean['change_quarter'] = airqualitydata_clean['date_of_last_change'].dt.quarter
airqualitydata_clean['days_since_change'] = (pd.Timestamp.now() - airqualitydata_clean['date_of_last_change']).dt.days

In [27]:
# Cyclical encoding for seasons
airqualitydata_clean['change_month_sin'] = np.sin(2*np.pi*airqualitydata_clean['date_of_last_change'].dt.month/12)
airqualitydata_clean['change_month_cos'] = np.cos(2*np.pi*airqualitydata_clean['date_of_last_change'].dt.month/12)

In [28]:
# Method complexity (word count)
airqualitydata_clean['method_complexity'] = airqualitydata_clean['method'].str.split().str.len()

# Equipment type from method text
airqualitydata_clean['equipment_type'] = np.where(
    airqualitydata_clean['method'].str.contains('INSTRUMENTAL', case=False), 
    'Analytical', 
    'Manual'
)

In [29]:

# Season-concentration interaction
airqualitydata_clean['summer_highs'] = (airqualitydata_clean['date_of_last_change'].dt.month.isin([6,7,8])) & (airqualitydata_clean['lvl1_monitor_concentration'] > 60)

In [30]:
# Previous day's concentration
airqualitydata_clean['prev_day_concentration'] = airqualitydata_clean.groupby('site_number')['lvl1_monitor_concentration'].shift(1)

In [31]:
# Site-level percentiles
airqualitydata_clean['site_percentile'] = airqualitydata_clean.groupby('site_number')['lvl1_monitor_concentration'].rank(pct=True)

# County-level volatility
airqualitydata_clean['county_volatility'] = airqualitydata_clean.groupby(['county_code','change_year'])['lvl1_monitor_concentration'].transform('std')

In [32]:
airqualitydata_clean.to_csv('cleaned_air_quality.csv', index=False)